name: Avili
favicon: null
layout_spectrum: 0.2485
typography_spectrum: 0.49759
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4f5fa'
    - '#a8b3c5'
    - '#181619'
    - '#8e95a5'
    - '#4d4948'
  brandStrength: 0.4352171996142715
  lightness: 0.014854633715003729
  saturation: 0.8075789087451994
  rhythmicContrast: 0.25
purpose: []
