name: Avili
favicon: null
layout_spectrum: 0.5137306025717407
typography_spectrum: 0.49759
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.4352171996142715
  lightness: 0.014854633715003729
  saturation: 0.8075789087451994
  rhythmicContrast: 0.5166245682630688
purpose: []
